### ISSUE TITLE
Python 3.13 Compatibility Issue: pandas 1.5.3 Build Failure

### ISSUE THREAD

**Issue by Aartighanghoriya** [rysweet/azure-tenant-grapher#611]
"The installation failed due to a compilation error with pandas 1.5.3. The issue is that pandas 1.5.3 is incompatible with Python 3.13 (which you're using) because it tries to use deprecated C API functions.

Root Cause:
The project requires Python 3.12+ (as specified in pyproject.toml)
You're using Python 3.13.9
The dependency littleballoffur requires pandas<2.0, which means pandas 1.5.3
pandas 1.5.3 doesn't compile on Python 3.13 due to C API changes

Solution:
You need to use Python 3.12 instead of Python 3.13. Here's how to fix it:
Install Python 3.12 if you don't have it
Create a new virtual environment with Python 3.12:
Activate the environment and install:

Alternatively, you could try updating the pandas constraint in the dependencies, but that might break littleballoffur compatibility. The safest approach is to use Python 3.12 as the project likely hasn't been tested with Python 3.13 yet.
"
